export enum NotificationType {
  SYSTEM = "SYSTEM",
  TASK_APPROVAL = "TASK_APPROVAL",
  TASK_REVIEW = "TASK_REVIEW",
  TASK_ASSIGNED = "TASK_ASSIGNED",
  TASK_SUBMITTED = "TASK_SUBMITTED",
  TASK_GRADED = "TASK_GRADED",
}
